Restricted oauth token ttl in Redis to 6h.
adobe-apiplatform/api-gateway-request-validation pull request #21
Opened 2017-06-08 10:59 UTC by andralungu

@ddragosd, @cristianconstantin ping.

2017-06-08 20:56 UTC, cristianconstantin requested changes

2017-06-08 20:56 UTC, cristianconstantin commented on src/lua/api-gateway/validation/oauth2/oauthTokenValidator.lua
> +    self:setKeyInRedis(cacheLookupKey, "token_json", math.min( expire_at_ms_utc - (os.time() * 1000), REDIS_CACHE_TTL ), cachingObjString)
The third parameter of the `setKeyInRedis` method need to be a timestamp, not a TTL, so this should probably be ```math.min( expire_at_ms_utc, (os.time()  + MAX_REDIS_CACHE_TTL) * 1000) )``` 
(if the max TTL is specified in seconds)

2017-06-09 03:49 UTC, ddragosd commented on src/lua/api-gateway/validation/oauth2/oauthTokenValidator.lua
> +    self:setKeyInRedis(cacheLookupKey, "token_json", math.min( expire_at_ms_utc - (os.time() * 1000), REDIS_CACHE_TTL ), cachingObjString)
:+1:

2017-06-09 07:30 UTC, andralungu commented
@cristianconstantin, PR updated

2017-06-09 20:32 UTC, cristianconstantin requested changes

2017-06-09 20:32 UTC, cristianconstantin commented on src/lua/api-gateway/validation/validator.lua
> +    rediss:set_timeout(5000)
I would have this as part of another 'pull-request'. Just reducing the timeout only helps failing the requests faster, but what we actually want is to have errors while caching the token not affecting the API GW serving the request.

2017-06-12 07:36 UTC, andralungu commented
@cristianconstantin, the set_timout was removed. I will open a separate PR for that once this one gets merged.

2017-06-12 13:00 UTC, andralungu commented
The tests were failing with `pattern "[error]" should not match any line in error.log but matches line "2017/06/12 12:50:53 [error] 554\#0: *2 lua entry thread aborted: runtime error: access_by_lua(nginx.conf:65):1: attempt to index field 'validation' (a nil value)" (req 1)'` because I tried to make the TTL customisable via `ngx.var.max_oauth_redis_cache_ttl`. 

The problem is that init_worker_by_lua does not have access to ngx.var, environment variables, etc.

2017-06-13 06:48 UTC, cristianconstantin commented on src/lua/api-gateway/validation/oauth2/oauthTokenValidator.lua
> +    self:setKeyInRedis(cacheLookupKey, "token_json", math.min(expire_at_ms_utc, (os.time() + REDIS_CACHE_TTL) * 1000), cachingObjString)
The max TTL should be allowed to be overwritten by an external variable, so that we can update the max TTL without touching the code.

2017-06-13 11:55 UTC, andralungu commented
Deployed and tested on dev.

2017-06-13 11:55 UTC, merged