update to support different host
adobe-apiplatform/api-gateway-request-validation pull request #22
Opened 2017-06-08 12:26 UTC by atrifan

@cristianconstantin, @andralungu

2017-06-08 20:40 UTC, cristianconstantin commented on src/lua/api-gateway/validation/oauth2/userProfileValidator.lua
> -        if ( self:isProfileValid(cachedUserProfile) == true ) then
Was this line accidentally removed?

2017-06-08 20:49 UTC, cristianconstantin commented on src/lua/api-gateway/validation/validator.lua
> +    if self.redisHost then
I believe you also need a second variable, for the Redis read replica.
I would rather change the static `redis_RO_upstream` and `redis_RW_upstream` variables to class members of the `"api-gateway.validation.validator"` base class have them overwritten when this class is extended by `oauthTokenValidator`.

2017-06-09 20:39 UTC, cristianconstantin requested changes

2017-06-09 20:39 UTC, cristianconstantin commented on src/lua/api-gateway/validation/oauth2/userProfileValidator.lua
> -        if ( self:isProfileValid(cachedUserProfile) == true ) then
Was this line accidentally removed?

2017-06-13 17:20 UTC, atrifan commented on src/lua/api-gateway/validation/oauth2/userProfileValidator.lua
> -        if ( self:isProfileValid(cachedUserProfile) == true ) then
it's fixed now can u check again? Thanks

2017-06-14 18:47 UTC, ddragosd commented
👍  LGTM. didn't test it though.

2017-06-14 23:13 UTC, atrifan commented
@ddragosd existing tests are passing are you referring at adding additional tests to check upstreams?

2017-06-15 11:43 UTC, andralungu commented on dist/maven/pom.xml
> +    <version>1.2.8-SNAPSHOT</version>
I guess this gets automagically updated by the maven release plugin.

2017-06-15 11:44 UTC, andralungu approved these changes

2017-06-15 16:02 UTC, cristianconstantin approved these changes

2017-06-21 07:12 UTC, merged