Multiple Redis authentication sources
adobe-apiplatform/api-gateway-request-validation pull request #26
Opened 2017-08-04 11:27 UTC by vdatcu

- Add multiple redis authentication sources
- Change the way connections are requested; now the caller should provide cluster_type, read_only if the connection is to be made using the existing mechanism, or provide override_options table if they want to go straight to the Redis instance, without upstream resolution
- The existing cluster types are "apiKey" and "oauth"; more can be added in the redisConnectionConfiguration file
- Replace env variable names

2017-08-04 11:27 UTC, vdatcu commented
Opening PR to keep people in the loop

2017-08-04 13:18 UTC, atrifan requested changes

2017-08-04 13:18 UTC, atrifan commented on src/lua/api-gateway/validation/validator.lua
> +    local ok, redisread = redisConnectionProvider:getConnection("apiKey", true);
This is a base validator - the class that extends this one should be able to dictate what type of redis cache to use. In this case you are forcing apiKey all the way - self.redis_RO_upstream was good

2017-08-04 13:18 UTC, atrifan commented on src/lua/api-gateway/validation/validator.lua
> +    local ok, redisread = redisConnectionProvider:getConnection("apiKey", true);
the above comment applies here as well

2017-08-04 13:18 UTC, atrifan commented on src/lua/api-gateway/redis/redisConnectionProvider.lua
> +function RedisConnectionProvider:getConnection(cache_type, read_only, override_options)
this looks great - the only thing is that I don't always have a read_only replica and this beeing open source should provide bigger flexibility

2017-08-04 13:18 UTC, atrifan commented on src/lua/api-gateway/redis/redisConnectionProvider.lua
> +function RedisConnectionProvider:getConnection(cache_type, read_only, override_options)
I would keep the old implementation with the upstream I would do some mapings based on the known upstreams and just offer override_options

2017-09-14 12:16 UTC, atrifan approved these changes

2017-09-14 12:16 UTC, merged