Missing validators on one level should go to the next validators set
adobe-apiplatform/api-gateway-request-validation pull request #50
Opened 2018-02-26 13:48 UTC by andralungu

2018-02-27 08:25 UTC, constantincristian requested changes

2018-02-27 08:25 UTC, constantincristian commented on src/lua/api-gateway/validation/validatorsHandler.lua
> -        ngx.exit(ngx.HTTP_OK)
Can we add a unit/integration test that would demonstrate this indeed fixes the issue?

2018-02-28 11:21 UTC, andralungu commented
@constantincristian, I was trying to solve the task one subtask at a time 😄 
Please have another look.

2018-03-01 11:06 UTC, atrifan approved these changes

2018-03-01 11:06 UTC, atrifan commented on src/lua/api-gateway/validation/validatorsHandler.lua
> +            ngx.var[k] = v
👍

2018-03-01 11:06 UTC, atrifan commented on src/lua/api-gateway/validation/validatorsHandler.lua
> +    local reqs_count = table.maxn(reqs)
👍

2018-03-01 11:34 UTC, vdatcu approved these changes

2018-03-01 11:43 UTC, atrifan requested changes

2018-03-01 11:43 UTC, atrifan commented on src/lua/api-gateway/validation/validatorsHandler.lua
> +            ngx.var[k] = v
```if v ~= ngx.null then
                ngx.var[k] = v
            end```

2018-03-01 13:26 UTC, andralungu commented
@atrifan please have another look

2018-03-02 12:05 UTC, merged