[WS-11856] Fix logger decorator for callbacks
adobe-apiplatform/api-gateway-request-validation pull request #60
Opened 2018-04-02 14:33 UTC by atrifan

As a developer i want to fix the logger decorator so all messages are logged.

Nothing that is executed in the kinesis callback is logged. The logger is enhanced with ngx.var.requestId but the timer callback is detached from the request's context and can not access this variable (see logger.lua from api-gateway-request-validation module);

the logger decorator can be improved by selecting what type of information should debug.getinfo return (line 15 from logger.lua file);
Suggested improvement:
local debugInfo =  debug.getinfo(2, "nSl")
Reference: https://www.lua.org/pil/23.1.html

2018-04-03 10:13 UTC, corinapurcarea requested changes

2018-04-03 10:13 UTC, corinapurcarea commented on src/lua/api-gateway/util/logger.lua
> +        return level, "[", debugInfo.short_src,
IMO, if status is true then req_id should be result else it should be set to "N/A".

2018-04-03 13:41 UTC, corinapurcarea approved these changes
👍

2018-04-04 07:28 UTC, vdatcu approved these changes
:+1:

2018-04-04 07:31 UTC, merged