Refactor oauth client
adobe-apiplatform/api-gateway-request-validation pull request #67
Opened 2018-07-02 07:00 UTC by corinapurcarea

- extract location for validating the user profile in a class field;
- make function pushMetrics more general;

2018-07-02 08:41 UTC, atrifan requested changes

2018-07-02 08:41 UTC, atrifan commented on src/lua/api-gateway/validation/oauth2/userProfileValidator.lua
> +_M.PROFILE_VALIDATION_LOCATION = "/validate-user"
is this static - why do you need to have it with uppercase?

2018-07-02 08:45 UTC, andralungu approved these changes
👍

2018-07-02 15:21 UTC, bogdanciuca approved these changes
👍

2018-07-03 07:27 UTC, atrifan approved these changes

2018-07-03 08:01 UTC, merged